[package]
name = "gs11n"
version = "0.1.0"
edition = "2018"
description = "Utililties need for GS11N"
license = "MIT OR Apache-2.0"
repository = "https://github.com/psionic12/gs11n"

[dependencies]
rustc-hash = "1.1.0"
lazy_static = "1.4.0"
ctor = "0.1.3"

[dev-dependencies]
test-cdylib = "1.1.0"
libloading = "0.7.2"